import type { StoredScan } from "@/types/scan";
import { SEVERITY_LABEL } from "@/components/dashboard/severity";

function line(label: string, value: string | number | boolean): string {
  return `${label.padEnd(24)}${String(value)}`;
}

/** Builds a plain-text audit report from a stored scan. No fabricated values. */
export function buildReportText({ url, scannedAt, result }: StoredScan): string {
  const { scan, seo, ai } = result;
  const out: string[] = [];

  out.push("BrandVizi — SEO Audit Report");
  out.push("=".repeat(60));
  out.push(line("URL", url));
  out.push(line("Scanned at", new Date(scannedAt).toLocaleString()));
  out.push("");

  out.push("SCORE");
  out.push("-".repeat(60));
  out.push(line("SEO score", `${Math.round(seo.score.score)} / 100`));
  if (seo.score.grade) out.push(line("Grade", seo.score.grade));
  out.push(line("Critical", seo.score.summary.critical));
  out.push(line("High", seo.score.summary.high));
  out.push(line("Medium", seo.score.summary.medium));
  out.push(line("Low", seo.score.summary.low));
  out.push("");

  out.push("METADATA");
  out.push("-".repeat(60));
  out.push(line("Title", scan.title || "Not Found"));
  out.push(line("Meta description", scan.meta_description || "Not Found"));
  out.push(line("Canonical", scan.canonical || "Not Found"));
  out.push(line("Meta robots", scan.meta_robots || "Not Found"));
  out.push(line("Language", scan.language || "Not Found"));
  out.push(line("Charset", scan.charset || "Not Found"));
  out.push(line("Viewport", scan.viewport || "Not Found"));
  out.push(line("Favicon", scan.favicon || "Not Found"));
  out.push("");

  out.push("WEBSITE STATISTICS");
  out.push("-".repeat(60));
  out.push(line("H1 count", scan.h1_count));
  out.push(line("H2 count", scan.h2_count));
  out.push(line("Images", scan.images));
  out.push(line("Images missing alt", scan.missing_alt));
  out.push(line("Internal links", scan.internal_links));
  out.push(line("robots.txt found", scan.robots_found ? "Yes" : "No"));
  out.push(line("Sitemap found", scan.sitemap_found ? "Yes" : "No"));
  out.push("");

  out.push(`SEO ISSUES (${seo.issues.length})`);
  out.push("-".repeat(60));
  if (seo.issues.length === 0) {
    out.push("No issues found.");
  } else {
    seo.issues.forEach((issue, index) => {
      out.push(`${index + 1}. [${SEVERITY_LABEL[issue.severity]}] ${issue.message}`);
      if (issue.category) out.push(`   Category: ${issue.category}`);
      if (issue.recommendation) out.push(`   Fix: ${issue.recommendation}`);
      out.push("");
    });
  }

  out.push(`AI RECOMMENDATIONS (${ai.recommendations.length})`);
  out.push("-".repeat(60));
  if (ai.recommendations.length === 0) {
    out.push("No AI recommendations returned for this scan.");
  } else {
    [...ai.recommendations]
      .sort((a, b) => a.priority - b.priority)
      .forEach((item, index) => {
        out.push(`${index + 1}. ${item.title} (priority ${item.priority})`);
        if (item.reason) out.push(`   Why: ${item.reason}`);
        if (item.action) out.push(`   Action: ${item.action}`);
        if (item.impact) out.push(`   Impact: ${item.impact}`);
        if (item.estimated_effort) out.push(`   Effort: ${item.estimated_effort}`);
        out.push("");
      });
  }

  out.push("=".repeat(60));
  out.push("Generated by BrandVizi — single-page scan.");
  return out.join("\n");
}

export function downloadReport(scan: StoredScan): void {
  const blob = new Blob([buildReportText(scan)], { type: "text/plain;charset=utf-8" });
  const href = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  let host = "report";
  try {
    host = new URL(scan.url).hostname.replace(/^www\./, "");
  } catch {
    /* keep default */
  }
  anchor.href = href;
  anchor.download = `brandvizi-report-${host}-${scan.scannedAt.slice(0, 10)}.txt`;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(href);
}
