import { createFileRoute, Link } from "@tanstack/react-router";
import { useRef, useState, type FormEvent } from "react";
import { AlertTriangle, ArrowLeft, Bot, CheckCircle2, ExternalLink, Globe, Loader2, RefreshCw, Search, ShieldCheck, XCircle } from "lucide-react";
import { SiteNav } from "@/components/site-nav";
import { AIChatPanel } from "@/components/ai-chat-panel";
import { DashboardSection } from "@/components/dashboard/section";
import { SEVERITY_BADGE, SEVERITY_LABEL } from "@/components/dashboard/severity";
import { getScanRecommendations, siteAudit, type AIRecommendationResult, type CrawlReport, type SEOIssue } from "@/lib/api";
import { toApiError, type ApiError } from "@/lib/api-error";
import { validateWebsiteUrl } from "@/lib/url-validation";

export const Route = createFileRoute("/multi-page-audit")({
  head: () => ({ meta: [{ title: "Multi-Page Site Audit — RankX" }, { name: "description", content: "Analyze multiple pages of your website and identify SEO issues across the site." }, { name: "robots", content: "noindex" }] }),
  component: MultiPageAuditPage,
});

function SeverityBadge({ severity }: { severity: SEOIssue["severity"] }) {
  return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${SEVERITY_BADGE[severity]}`}>{SEVERITY_LABEL[severity]}</span>;
}

function Issues({ issues, empty }: { issues: SEOIssue[]; empty: string }) {
  if (!issues.length) return <p className="text-sm text-muted-foreground">{empty}</p>;
  return <div className="space-y-3">{issues.map((issue) => <article key={`${issue.rule_id}-${issue.message}`} className="rounded-2xl border border-border bg-secondary/30 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold text-foreground">{issue.message}</p><p className="mt-1 text-sm text-muted-foreground">{issue.recommendation}</p></div><SeverityBadge severity={issue.severity} /></div></article>)}</div>;
}

function Results({ report, recommendations, recommendationsError, onNewAudit }: { report: CrawlReport; recommendations: AIRecommendationResult | null; recommendationsError: ApiError | null; onNewAudit: () => void }) {
  const { summary } = report;
  const metrics = [
    ["Overall SEO Score", `${Math.round(summary.average_score)}/100`], ["Grade", summary.grade], ["Pages Analyzed", String(summary.total_pages)], ["Failed Pages", String(summary.failed_pages)],
    ["Critical Issues", String(summary.critical)], ["High Issues", String(summary.high)], ["Medium Issues", String(summary.medium)], ["Low Issues", String(summary.low)],
  ];
  const context = `Multi-page audit: ${summary.total_pages} pages, average score ${Math.round(summary.average_score)}, grade ${summary.grade}.`;
  return <div className="min-h-screen bg-secondary/30"><SiteNav /><main className="mx-auto max-w-7xl space-y-6 px-6 py-10 sm:py-14">
    <header className="flex flex-wrap items-start justify-between gap-6"><div><div className="inline-flex items-center gap-2 rounded-full bg-accent px-3 py-1 text-xs font-semibold text-primary"><Globe className="h-3.5 w-3.5" /> Multi-page report</div><h1 className="mt-3 text-3xl font-extrabold tracking-tight sm:text-4xl">Multi-Page Site Audit</h1><p className="mt-2 text-sm text-muted-foreground">Results for {summary.total_pages} crawled page{summary.total_pages === 1 ? "" : "s"}.</p></div><button onClick={onNewAudit} className="inline-flex items-center gap-2 rounded-xl border border-border bg-white px-4 py-2.5 text-sm font-semibold transition hover:bg-secondary"><RefreshCw className="h-4 w-4" /> New audit</button></header>
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{metrics.map(([label, value]) => <div key={label} className="rounded-2xl border border-border bg-white p-5 shadow-[var(--shadow-card)]"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-extrabold tracking-tight text-foreground">{value}</p></div>)}</section>
    <DashboardSection icon={ShieldCheck} title="Crawl Status" description={summary.crawl_complete ? "The requested crawl completed successfully." : "The crawl completed with one or more page failures."}><div className="grid gap-4 text-sm sm:grid-cols-3"><p><strong>Robots.txt:</strong> {summary.robots_txt_found ? "Found" : "Not found"}</p><p><strong>Sitemap:</strong> {summary.sitemap_found ? "Found" : "Not found"}</p><p><strong>Crawl status:</strong> {summary.crawl_complete ? "Complete" : "Partial"}</p>{summary.sitemap_urls.length > 0 && <p className="sm:col-span-3 break-all text-muted-foreground"><strong>Sitemaps:</strong> {summary.sitemap_urls.join(", ")}</p>}</div></DashboardSection>
    <DashboardSection icon={Search} title="Pages Analyzed" description="Review scores and the most important issues for each crawled page."><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b border-border text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="p-3">URL</th><th className="p-3">Score</th><th className="p-3">Grade</th><th className="p-3">Issues</th><th className="p-3">Important issues</th></tr></thead><tbody>{report.pages.map((page) => <tr key={page.url} className="border-b border-border/70 last:border-0"><td className="max-w-[280px] p-3"><a href={page.url} target="_blank" rel="noopener noreferrer" className="inline-flex break-all font-medium text-primary hover:underline">{page.url}<ExternalLink className="ml-1 mt-0.5 h-3.5 w-3.5 shrink-0" /></a></td><td className="p-3 font-bold">{Math.round(page.score)}</td><td className="p-3">{page.grade}</td><td className="p-3">{page.issues.length}</td><td className="p-3"><div className="flex flex-wrap gap-1">{page.issues.slice(0, 2).map((issue) => <SeverityBadge key={issue.rule_id} severity={issue.severity} />)}{page.issues.length > 2 && <span className="text-xs text-muted-foreground">+{page.issues.length - 2} more</span>}</div></td></tr>)}</tbody></table></div>{!report.pages.length && <p className="mt-4 text-sm text-muted-foreground">No pages were returned by the crawl.</p>}</DashboardSection>
    <DashboardSection icon={AlertTriangle} title="Site-Level Issues" description="Issues that affect the website as a whole, rather than one page."><Issues issues={report.site_issues} empty="No site-level issues were returned." /></DashboardSection>
    <DashboardSection icon={report.failures.length ? XCircle : CheckCircle2} title="Crawl Failures" description={report.failures.length ? "These pages could not be crawled." : "All requested pages were crawled successfully."}>{report.failures.length ? <div className="space-y-3">{report.failures.map((failure) => <div key={failure.url} className="rounded-2xl border border-destructive/20 bg-destructive/5 p-4"><p className="break-all font-semibold">{failure.url}</p><p className="mt-1 text-sm text-muted-foreground">{failure.reason}</p></div>)}</div> : null}</DashboardSection>
    <DashboardSection icon={Bot} title="AI Recommendations" description="Priority actions based on this persisted site audit.">{recommendationsError ? <p className="text-sm text-destructive">Audit completed, but AI recommendations could not be loaded.</p> : !recommendations ? <div className="flex items-center gap-2 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin" /> Preparing recommendations…</div> : recommendations.recommendations.length ? <div className="space-y-4">{recommendations.recommendations.map((item) => <article key={`${item.priority}-${item.title}`} className="rounded-2xl border border-border bg-secondary/30 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-primary">Priority {item.priority}</p><h3 className="mt-1 font-bold">{item.title}</h3></div><span className="rounded-full bg-accent px-2.5 py-1 text-xs font-semibold text-primary">Impact: {item.impact}</span></div><p className="mt-3 text-sm text-muted-foreground">{item.reason}</p><p className="mt-3 text-sm"><strong>Action:</strong> {item.action}</p><p className="mt-2 text-sm"><strong>Estimated effort:</strong> {item.estimated_effort}</p>{item.source_issue_type && <p className="mt-2 text-xs text-muted-foreground">Source: {item.source_issue_type} · Affects {item.affected_page_count} page(s)</p>}{item.affected_urls.length > 0 && <p className="mt-1 break-all text-xs text-muted-foreground">{item.affected_urls.join(", ")}</p>}{item.example && <p className="mt-2 text-sm text-muted-foreground"><strong>Example:</strong> {item.example}</p>}</article>)}</div> : <p className="text-sm text-muted-foreground">AI recommendations are temporarily unavailable. SEO scores, page results, site issues, and crawl failures are still available above.</p>}</DashboardSection>
  </main><AIChatPanel context={context} /></div>;
}

function MultiPageAuditPage() {
  const [url, setUrl] = useState(""); const [maxPages, setMaxPages] = useState(20); const [formError, setFormError] = useState<string | null>(null); const [auditError, setAuditError] = useState<ApiError | null>(null); const [report, setReport] = useState<CrawlReport | null>(null); const [recommendations, setRecommendations] = useState<AIRecommendationResult | null>(null); const [recommendationsError, setRecommendationsError] = useState<ApiError | null>(null); const [loading, setLoading] = useState(false); const controllerRef = useRef<AbortController | null>(null);
  async function submit(event: FormEvent) { event.preventDefault(); const result = validateWebsiteUrl(url); if (!result.ok) return setFormError(result.message); if (!Number.isInteger(maxPages) || maxPages < 1 || maxPages > 100) return setFormError("Choose a whole number between 1 and 100 pages."); setFormError(null); setAuditError(null); setRecommendations(null); setRecommendationsError(null); setLoading(true); const controller = new AbortController(); controllerRef.current = controller; try { const nextReport = await siteAudit(result.url, maxPages, controller.signal); if (!nextReport.pages.length) throw new Error("The audit returned no pages."); setReport(nextReport); if (nextReport.scan_id === null) { setRecommendationsError({ name: "ApiError", title: "Recommendations unavailable", message: "The completed audit did not include a scan ID.", code: "unknown" } as ApiError); return; } try { setRecommendations(await getScanRecommendations(nextReport.scan_id, controller.signal)); } catch (error) { if (!controller.signal.aborted) setRecommendationsError(toApiError(error)); } } catch (error) { if (!controller.signal.aborted) setAuditError(toApiError(error)); } finally { if (!controller.signal.aborted) setLoading(false); controllerRef.current = null; } }
  function cancel() { controllerRef.current?.abort(); controllerRef.current = null; setLoading(false); }
  if (report) return <Results report={report} recommendations={recommendations} recommendationsError={recommendationsError} onNewAudit={() => { setReport(null); setRecommendations(null); setRecommendationsError(null); setAuditError(null); }} />;
  return <div className="min-h-screen"><SiteNav /><main className="mx-auto max-w-2xl px-6 py-16 sm:py-24"><Link to="/" className="inline-flex items-center gap-2 text-sm font-medium text-primary hover:underline"><ArrowLeft className="h-4 w-4" /> Back to home</Link><div className="mt-8 rounded-3xl border border-border bg-white p-6 shadow-[var(--shadow-card)] sm:p-10"><div className="inline-flex rounded-full bg-accent px-3 py-1 text-xs font-semibold text-primary">Multi-page analysis</div><h1 className="mt-4 text-3xl font-extrabold tracking-tight sm:text-4xl">Multi-Page Site Audit</h1><p className="mt-3 text-muted-foreground">Analyze multiple pages of your website and identify SEO issues across the site.</p>{auditError ? <div className="mt-6 rounded-2xl border border-destructive/20 bg-destructive/5 p-4 text-sm text-destructive"><p className="font-semibold">{auditError.title}</p><p className="mt-1">{auditError.message}</p></div> : null}<form onSubmit={submit} className="mt-8 space-y-5"><label className="block text-sm font-semibold">Website URL<input value={url} onChange={(e) => setUrl(e.target.value)} disabled={loading} placeholder="https://yourwebsite.com" className="mt-2 w-full rounded-xl border border-border px-4 py-3 outline-none transition focus:border-primary focus:ring-4 focus:ring-primary/10 disabled:bg-secondary" /></label><label className="block text-sm font-semibold">Maximum Pages<input type="number" min={1} max={100} step={1} value={maxPages} onChange={(e) => setMaxPages(Number(e.target.value))} disabled={loading} className="mt-2 w-full rounded-xl border border-border px-4 py-3 outline-none transition focus:border-primary focus:ring-4 focus:ring-primary/10 disabled:bg-secondary" /></label>{formError && <p className="text-sm text-destructive">{formError}</p>}{loading && <div className="rounded-2xl bg-accent p-4 text-sm text-primary"><div className="flex items-center gap-2 font-semibold"><Loader2 className="h-4 w-4 animate-spin" /> Analyzing your website…</div><p className="mt-1 text-primary/80">Crawling and checking multiple pages. This may take a little longer than a single-page audit.</p></div>}<div className="flex flex-wrap gap-3"><button disabled={loading} className="inline-flex items-center gap-2 rounded-xl bg-[image:var(--gradient-primary)] px-5 py-3 text-sm font-semibold text-white shadow-[var(--shadow-glow)] disabled:cursor-not-allowed disabled:opacity-60">{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Search className="h-4 w-4" />} Start Multi-Page Audit</button>{loading && <button type="button" onClick={cancel} className="rounded-xl border border-border px-5 py-3 text-sm font-semibold hover:bg-secondary">Cancel</button>}</div></form></div></main><AIChatPanel /></div>;
}
