import { useState } from "react";
import { Bot, ChevronDown, Lightbulb, Wrench } from "lucide-react";
import type { AIRecommendation } from "@/types/scan";
import { DashboardSection } from "./section";
import { EmptyState } from "./empty-state";

function priorityLabel(priority: number): { label: string; className: string } {
  if (priority <= 1) return { label: "High Priority", className: "bg-red-50 text-red-700 ring-1 ring-red-200" };
  if (priority === 2) return { label: "Medium Priority", className: "bg-amber-50 text-amber-700 ring-1 ring-amber-200" };
  return { label: "Low Priority", className: "bg-blue-50 text-blue-700 ring-1 ring-blue-200" };
}

function RecommendationCard({ item, defaultOpen }: { item: AIRecommendation; defaultOpen: boolean }) {
  const [open, setOpen] = useState(defaultOpen);
  const priority = priorityLabel(item.priority);

  return (
    <article className="overflow-hidden rounded-2xl border border-border bg-white shadow-sm transition hover:border-primary/30">
      <button
        type="button"
        onClick={() => setOpen((value) => !value)}
        aria-expanded={open}
        className="flex w-full items-start justify-between gap-4 p-5 text-left"
      >
        <div className="min-w-0">
          <h3 className="text-base font-semibold text-foreground">{item.title}</h3>
          <div className="mt-2 flex flex-wrap items-center gap-2">
            <span className={`rounded-full px-2.5 py-0.5 text-xs font-semibold ${priority.className}`}>
              {priority.label}
            </span>
            {item.impact && (
              <span className="rounded-full bg-secondary px-2.5 py-0.5 text-xs font-medium text-muted-foreground">
                Impact: {item.impact}
              </span>
            )}
            {item.estimated_effort && (
              <span className="rounded-full bg-secondary px-2.5 py-0.5 text-xs font-medium text-muted-foreground">
                Effort: {item.estimated_effort}
              </span>
            )}
          </div>
        </div>
        <ChevronDown className={`mt-1 h-5 w-5 shrink-0 text-primary transition ${open ? "rotate-180" : ""}`} />
      </button>

      {open && (
        <div className="space-y-4 border-t border-border px-5 pb-5 pt-4">
          {item.reason && (
            <div>
              <div className="mb-1.5 flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                <Lightbulb className="h-3.5 w-3.5" /> Why?
              </div>
              <p className="text-sm leading-relaxed text-foreground/90">{item.reason}</p>
            </div>
          )}
          {item.action && (
            <div>
              <div className="mb-1.5 flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                <Wrench className="h-3.5 w-3.5" /> Recommended Action
              </div>
              <p className="rounded-xl border border-border bg-secondary/50 p-4 text-sm leading-relaxed text-foreground">
                {item.action}
              </p>
            </div>
          )}
        </div>
      )}
    </article>
  );
}

export function AiRecommendations({ recommendations }: { recommendations: AIRecommendation[] }) {
  const sorted = [...recommendations].sort((a, b) => a.priority - b.priority);

  return (
    <DashboardSection
      icon={Bot}
      title="AI Recommendations"
      description="Generated by the RankX AI engine from this scan."
    >
      {sorted.length === 0 ? (
        <EmptyState
          icon={Bot}
          title="No AI recommendations returned"
          description="The AI engine did not return recommendations for this scan."
        />
      ) : (
        <div className="space-y-4">
          {sorted.map((item, index) => (
            <RecommendationCard key={`${item.title}-${index}`} item={item} defaultOpen={index < 2} />
          ))}
        </div>
      )}
    </DashboardSection>
  );
}
